image: docker:latest

stages:
  - package

before_script:
  - docker version
  - docker login -u $HUANSI_YL_USER -p $HUANSI_YL_PASSWORD $HUANSI_REGISTRY_URL


# 打包并构建镜像
package:
  stage: package
  retry: 1
  image: adoptopenjdk/maven-openjdk11
  tags:
    - k8s.test.iot.hangzhou
  script:
    - echo "打包并构建镜像"
    - date -R
    - cd msa
    - mvn clean install -Ddockerfile.skip=false
  only:
    - dev
  after_script:
    - echo "镜像打包完毕,镜像如下:"
    - docker images | grep ${HUANSI_REGISTRY_URL}/${HUANSI_YL_REGISTRY_NAME}/thingsboard

