image: dockergitlabrunner_gitlab-runner:latest

stages:
  - package
  - push

#before_script:
#  - docker login -u $HUANSI_YL_USER -p $HUANSI_YL_PASSWORD $HUANSI_REGISTRY_URL

    
# 打包并构建镜像
package:
  stage: package
  retry: 1
  tags:
    - zhows-test
  script:
    - echo "打包并构建镜像"
    - date -R
    - docker info
    - mvn clean install -Ddockerfile.skip=false
  only:
    - dev
  after_script:
    - echo "镜像打包完毕,镜像如下:"
    - docker images | grep ${HUANSI_REGISTRY_URL}/${HUANSI_YL_REGISTRY_NAME}/thingsboard
    
# 打包并构建镜像
push:
  stage: push
  retry: 1
  tags:
    - zhows-test
  script:
    - echo "推送镜像"
    - docker info
  only:
    - dev
  after_script:
    - echo "镜像打包完毕,镜像如下:"
    - docker images | grep ${HUANSI_REGISTRY_URL}/${HUANSI_YL_REGISTRY_NAME}/thingsboard

