stages:
  - package
  - push
  
variables:
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  
before_script:
  - docker login -u $HUANSI_YL_USER -p $HUANSI_YL_PASSWORD $HUANSI_REGISTRY_URL

cache:
  paths:
    - .m2/repository/
    - application/target/
    
# 打包并构建镜像
package:
  stage: package
  image: 47.110.145.204:8084/huansiyl/mvn-jdk11-docker:latest
  retry: 1
  tags:
    - hz-k8s-iot-test
  script:
    - echo "打包并构建镜像"
    - mvn clean install -Dmaven.test.skip=true
    - ls application/target
  only:
    - dev
  after_script:
    - echo "镜像打包完毕,镜像如下:"
    - docker images | grep ${HUANSI_REGISTRY_URL}/${HUANSI_YL_REGISTRY_NAME}/thingsboard
    
# 打包并构建镜像
push:
  stage: push
  retry: 1
  tags:
    - zhows-test
  script:
    - echo "推送镜像"
    - docker info
  only:
    - dev
  after_script:
    - echo "镜像打包完毕,镜像如下:"
    - docker images | grep ${HUANSI_REGISTRY_URL}/${HUANSI_YL_REGISTRY_NAME}/thingsboard

