apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-node-pv-claim
  namespace: hsyl-iot
  labels:
    app: tb-node-upload
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-node-pv-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/upload"

